ISSUE #93 (solved) Code Optimization and UI Enhancements for Navbar Component
Puskar-Roy/create-my-api pull request #94
Opened 2024-10-17 06:00 UTC by Sumanth077s

# 🎯 Title and Issue Number

### Closes  #93 

# 🗒️ Checklist:

- [yes] I have mentioned the issue number in my Pull Request.
- [yes]  I have gone through `rules of when PR will get merged.` 
- [yes] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [yes] I have gone through

 Thank you for contributing!❤️ 

Don't forget to show some support by ⭐ the repository! 

Description:This pull request introduces several optimizations and minor UI improvements to the Navbar component. The changes improve code readability, maintainability, and styling consistency while preserving the original functionality.

Summary of Changes:
Code Consistency:

Renamed alata to montserrat to align with the imported font's name.
Renamed GIthubButton to GithubButton for consistent naming conventions.
Logic Simplification:

Replaced redundant {""} fragments with clean syntax.
Updated the toggleHamburger function to a concise arrow function.
UI and Styling Improvements:

Enhanced animation using transition-transform.
Adjusted spacing classes (e.g., mb-[50px] → mb-12) for better readability.
Improved layout consistency for the hamburger menu and navigation items.
Redundant Code Removal:

Removed unnecessary before: styles from <li> elements.
Simplified component structure by eliminating extra wrapper elements.
Readability Improvements:

Organized related sections (e.g., logo and menu) for better clarity.
Reformatted code with proper indentation for easier maintenance.
Impact:
Improved Code Quality: The component is now more readable and easier to maintain.
Consistent UI: Enhanced layout and animation for a smoother user experience.
Reduced Redundancy: Simplified logic and structure with no functional loss.

2024-10-17 06:00 UTC, Puskar-Roy commented
Hello @Sumanth077s, thank you for your pull request! We will review it shortly. 😇❣️
Your contributions help us grow and improve our project. Please make sure you have read and followed our [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Your efforts are appreciated, and we value your participation in our community. Don't forget to ⭐ our repository!
Happy coding!✨

2024-10-17 14:43 UTC, Puskar-Roy requested changes
can you please make the bg blur and correct the alignment of home actually its not visible in mobile screen
![Screenshot from 2024-10-17 20-11-35](https://github.com/user-attachments/assets/5d86c5a7-9926-4640-9722-ed11f8d747a7)

2024-10-17 15:36 UTC, Sumanth077s reviewed
Done changes

2024-10-17 17:12 UTC, Puskar-Roy requested changes
## The navbar is overlapping the top of the screen. Please fix this.
![Screenshot from 2024-10-17 22-37-42](https://github.com/user-attachments/assets/fa170f76-61b4-4651-9d8c-38f50b8e0c79)

2024-10-18 01:04 UTC, Sumanth077s reviewed
Made changes now it shouldn't overlap

2024-10-18 11:12 UTC, Puskar-Roy commented
> Made changes now it shouldn't overlap

## this is the bug!
![Screenshot from 2024-10-18 16-41-40](https://github.com/user-attachments/assets/7857ceea-ddb6-4b6d-98d8-c91ccab5e7ab)

2024-10-18 11:19 UTC, Sumanth077s commented
Bro how to check deployment

2024-10-18 11:25 UTC, Sumanth077s reviewed
Added changes

2024-10-20 12:44 UTC, Puskar-Roy commented
@Sumanth077s See :(
![Screenshot from 2024-10-20 18-14-09](https://github.com/user-attachments/assets/a24f85cb-887f-4741-a473-28f4bfc61e0d)

2024-10-20 12:46 UTC, Sumanth077s commented
How can I see the deployment after when I made changes

2024-10-20 12:47 UTC, Sumanth077s commented
It's asking for team access

2024-10-20 13:14 UTC, Sumanth077s reviewed
Check once

2024-10-22 18:06 UTC, Puskar-Roy commented
> Check once

hey @Sumanth077s i can not give you the team access due to the privacy reasons

2025-03-09 13:36 UTC, closed without merging